services:
  postgres:
    image: postgres:15
    container_name: cinema_postgres
    environment:
      POSTGRES_DB: cinema-booking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./cinema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./cine-data.sql:/docker-entrypoint-initdb.d/02-data.sql
    restart: unless-stopped

volumes:
  postgres_data: 