pipeline {
    agent any

    stages {
        stage('Pull code') {
            steps {
                git branch: 'main', url: 'https://github.com/Cinema-Booking-App/cinema-booking-backend.git'
            }
        }

        stage('Deploy to EC2') {
            steps {
                sshagent(credentials: ['ec2-ssh-key']) {
                    sh '''
                    ssh -o StrictHostKeyChecking=no ubuntu@<EC2_PUBLIC_IP> << 'EOF'
                    set -e
                    cd cinema-booking-backend || exit 1

                    # Pull hoặc clone code
                    if [ ! -d .git ]; then
                        git clone https://github.com/Cinema-Booking-App/cinema-booking-backend.git .
                    else
                        git pull origin main
                    fi

                    # Cài môi trường
                    python3 -m venv venv
                    source venv/bin/activate
                    pip install -r requirements.txt

                    # Restart service
                    sudo systemctl restart myfastapi
                    EOF
                    '''
                }
            }
        }
    }
}
