pipeline {
    agent any

    environment {
        EC2_IP = "16.176.227.13"
        EC2_USER = "ubuntu"
        PEM_PATH = "D:/DEVOPS/AWS-EC2.pem"
    }

    stages {
        stage('Deploy to EC2') {
            steps {
                bat """
                ssh -o StrictHostKeyChecking=no -i "%PEM_PATH%" %EC2_USER%@%EC2_IP% " \
                cd ~/cinema-booking-backend && \
                if [ ! -d .git ]; then git clone https://github.com/Cinema-Booking-App/cinema-booking-backend.git .; else git pull origin main; fi && \
                python3 -m venv venv && \
                source venv/bin/activate && \
                pip install -r requirements.txt && \
                sudo systemctl restart myfastapi \
                "
                """
            }
        }
    }
}
